name: Help Pages
version: 1.1
description: Make your own Help Pages!
author: Ultimate 
main: main.java.me.ultimate.HP.HelpPages

commands:
  help:
    description: View the help menu!
    usage: /help <page>