name: Help Pages
version: 1.6.0
description: Make your own Help Pages!
author: Ultimate 
main: me.paulbgd.bukkit.HP.HelpPages

commands:
  help:
    description: View the help menu!
    usage: /help <page> [submenu [submenu]]